version: '3.8'
services:
  dynamodb-local:
    command: -jar DynamoDBLocal.jar -inMemory
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - 8042:8000
    volumes:
      - .dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
