[project]
name = "wafr-automation-tool"
version = "0.1.0"
description = ""
readme = "../README.md"
requires-python = "==3.12.*"
dependencies = [
    "boto3>=1.36.5",
    "py-ocsf-models",
    "types-boto3[full]>=1.36.5",
]
