AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  WAFR Automation Tool

  Role for exporting assessments

Resources:
  AssessmentExportRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::<ACCOUNT_ID>:role/wafr-automation-tool-<ENV>-export-assessment'
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/WellArchitectedConsoleFullAccess
Outputs:
  AssessmentExportRole:
    Description: Assessment Export Role
    Value: !GetAtt AssessmentExportRole.Arn
