name: Deploy to AWS
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      STAGE: prod
      DEBUG: false
      INITIAL_USER_EMAIL: ${{ secrets.INITIAL_USER_EMAIL }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version-file: ./backend/.python-version
          cache: pip

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Setup Node and cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build Backend
        run: npm run build:backend
      - name: Build Frontend
        run: npm run build:webui

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Backend
        run: npm run deploy:backend -- --no-confirm-changeset

      - name: Deploy Frontend
        run: npm run deploy:webui:production -- --skip-nx-cache
