name: 'Tests check'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ts-backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node and cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
      - name: Install dependencies
        run: npm ci --prefer-offline
      - name: Start docker compose
        run: |
          docker compose up -d
          sleep 5
      - name: Prepare database
        run: npm run test:backend:init
      - name: Run tests
        run: npm run test:backend
  ts-frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node and cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
      - name: Install dependencies
        run: npm ci --prefer-offline
      - name: Run tests
        run: npm run test:webui
